### ISSUE TITLE
Ported to 3.0.35 and partially working.

### ISSUE THREAD

**Issue by hanzelpeter** [mwelchuk/usbtv#3]
Hello.

I have backported your driver to kernel 3.0.35.
I run it on ARM Udoo machine.

The problem is that after reboot the grabber works perfectly.
But after some minutes the picture is disorted and I have repeated artefacts in picture.

Is there something I can do about it?

**Comment by mwelchuk** [comment]
Hi Peter,

Sorry, been really busy and wasn't able to answer your question earlier.

I have very limited knowledge of the driver myself, I got it working well
enough for a small task I had but haven't needed it since.

I'd look at the latest version, see of that has moved on much and consider
a back port of that of there's any significant improvements.

Martyn

**Comment by hanzelpeter** [comment]
I have added dev_warn("user space too slow") to this method:

```
usbtv_image_chunk() 
{
    ....
  if (list_empty(...)  {
     /* No free buffers. Userspace likely too slow./*
    ...
    return
 }
}
```

And now we get this warning in kernel. 

Is there anything about it we can do?

**Comment by hu42ih** [comment]
I see the same issue when using mplayer (-vo fbdev) to display the video. mplayer uses 80% and more CPU.
