### ISSUE TITLE
Build in Ubuntu Xenial 

### ISSUE THREAD

**Issue by georgeuy** [mwelchuk/usbtv#4]
Hi Sir , do you think it is possible to adapt your code for my device tv- tuner?

[log.txt](https://github.com/mwelchuk/usbtv/files/360629/log.txt)

Sincerely George

**Comment by mwelchuk** [comment]
This driver didn't build as it's a back port for a much older kernel. Things have moved on.

As to whether it could be made to work for your device, hard to say, the information that you have sent me really doesn't give me the information that would be needed to determine that and I'm afraid I don't know enough about these devices to consider trying at this point. I just backported this driver from a newer kernel so that I could get the device I have working well enough to use it once.
